### ISSUE TITLE
$auth missing from context on client side (typing and global context)

### ISSUE THREAD

**Issue by emazyka** [Teranode/nuxt-module-alternatives#23] opened 2022-03-22 10:06 UTC
Hi,

I am trying to setup an oAuth strategy like github but it seems that `$auth` is missing from the context on the client side. So I cannot use the API like `context.$auth.loginWith('github') on my components. This is my nuxt config file. Is this something that may be an issue or do I miss some extra configuration?

```ts
import { defineNuxtConfig } from 'nuxt3';

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  modules: ['@nuxtjs-alt/proxy'],
  buildModules: ['@nuxtjs-alt/auth', '@nuxtjs-alt/axios', '@pinia/nuxt'],
  auth: {
    redirect: {
      callback: '/',
      login: '/',
    },
    strategies: {
      github: {
        client_id: 'xxxxxxx',
        client_secret: 'xxxxxxx',
      },
    },
  },
});
```

**Comment by emazyka** [comment] 2022-03-22 11:12
This is my `package.json`.

```json
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "dependencies": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@latest"
  },
  "devDependencies": {
    "@nuxtjs-alt/auth": "latest",
    "@nuxtjs-alt/axios": "latest",
    "@nuxtjs-alt/proxy": "latest",
    "@pinia/nuxt": "latest",
    "nuxt3": "latest",
    "pinia": "latest"
  }
}
```

**Comment by Teranode** [comment] 2022-03-22 11:16
What package manager are you using

**Comment by emazyka** [comment] 2022-03-22 11:18
I am using npm.

**Comment by Teranode** [comment] 2022-03-22 11:22
You're gonna have to experiment here. Either try using yarn 2 with the node module plug in (I don't use npm because it's dependency resolution isn't great)

Also try putting the modules in dependencies instead of devDependencies

**Comment by moonofmylife** [comment] 2022-03-22 11:24
I have the same problem. I use yarn.
axios is there, but auth is not
![image](https://user-images.githubusercontent.com/46625964/159471253-fd5946b6-20b0-41db-9b10-5f5e6a8bbd08.png)

**Comment by emazyka** [comment] 2022-03-22 13:34
It seems like there is an error on this [line](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/schemes/oauth2.ts#L132) causing this.

<img width="659" alt="Screenshot 2022-03-22 at 3 32 15 PM" src="https://user-images.githubusercontent.com/3679447/159493450-f5d6f76b-9322-4120-bde1-9f9ea00a8227.png">

**Comment by Adashi12** [comment] 2022-03-22 19:58
What API are you using?
How do you define the context?
Have you tried a different strategy?

Having the modules in "dependencies" in package.json and using yarn it works for me like this:
```
<script setup>
const ctx = useNuxtApp();
ctx.$auth.loginWith("...")
```

**Comment by Teranode** [comment] 2022-03-22 21:52
There's a lot of mixed reactions coming from nuxt overall.

Recently updated and removing the middleware from the module and adding it to the plugin definition fixes this context issue this issue is facing (I think), but then doing so forces the middleware to run globally even when the global param is turned off.

so I'm kind of stuck in a hard place on where to continue since more bugs keep popping up when nuxt updates.

**Comment by Teranode** [comment] 2022-03-22 21:55
Also everyone will need to start using `modules` instead of `buildModules` as per: https://github.com/nuxt/framework/pull/3830

**Comment by Teranode** [comment] 2022-03-22 22:23
I pushed another update, try to see if that works? (also updated the auth module readme so read that too)

**Comment by moonofmylife** [comment] 2022-03-23 09:49
:(

![image](https://user-images.githubusercontent.com/46625964/159671214-1677a371-966e-4ffc-988f-e0741826a22c.png)

**Comment by moonofmylife** [comment] 2022-03-23 10:12
I am temporarily using composable for this
```
import { Auth } from "@nuxtjs-alt/auth";

export const useAuth = () => {
  const { $auth } = useNuxtApp();

  return $auth as Auth;
};
```

```
const $auth = useAuth();
```

**Comment by Teranode** [comment] 2022-03-23 11:11
@moonofmylife update once more and try to see if that works?

**Comment by moonofmylife** [comment] 2022-03-24 08:48
> @moonofmylife update once more and try to see if that works?

Nothing has changed

**Comment by Teranode** [comment] 2022-03-24 09:13
Yea then I dont know how to help on this case. I've tried to create reproduceable results but currently dealing with middleware and layout bugs.

**Comment by emazyka** [comment] 2022-03-24 09:18
Hi @Teranode ,
Is this [line](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/schemes/oauth2.ts#L132) throwing an error for you as well? It seems like `ssrContext` is missing from context on the client side and when it's trying to resolve `$auth.ctx.ssrContext.req`, it throws an error. I've added optional chaining on that line with an empty string value as a fallback and it seems to work for me.

**Comment by moonofmylife** [comment] 2022-03-24 09:30
Typing doesn't work for me even for a local plugin. It looks like this is a problem of nuxt itself

**Comment by Teranode** [comment] 2022-03-24 09:49
@emazyka updated

@moonofmylife not sure can't really tell, in a global context `pinia` and `axios` shows up fine but `auth` comes up undefined until later (which shouldn't affect typing but it doesn't appear), so it might just be both.

**Comment by emazyka** [comment] 2022-03-24 10:06
@Teranode I've added a PR with the hot fix. If you could try it out that would be great. I hope this helps. Thank you.

**Comment by moonofmylife** [comment] 2022-03-24 10:43
> @emazyka updated
> 
> @moonofmylife not sure can't really tell, in a global context `pinia` and `axios` shows up fine but `auth` comes up undefined until later (which shouldn't affect typing but it doesn't appear), so it might just be both.

![image](https://user-images.githubusercontent.com/46625964/159899376-28bb4c16-5832-4c90-9482-96dc1d04f03c.png)
![image](https://user-images.githubusercontent.com/46625964/159899434-cd114176-a71f-4e89-af1d-9d69fe57d15e.png)

:(

**Comment by Denoder** [comment] 2022-03-27 22:20
There's no easy fix for this ( at least from what I see), was looking at different nuxt framework discussions https://github.com/nuxt/framework/search?q=callWithNuxt&type=discussions

The only solution I could come up with was to have auth be called within vue's `nextTick` function, or `onMounted` or using `setTimeout`. I've had to do this for the middleware to make it work, the original auth module used async/await and that doesn't work with nuxt3's current implementation of their module/plugin registration so I've had to change the initialization slightly.

I see a pull request made for this so maybe that will help with this: 
https://github.com/nuxt/nuxt.js/issues/13421
https://github.com/nuxt/framework/pull/3884

**Comment by Teranode** [comment] 2022-04-27 12:14
@skyroses hey, I've updated the auth module a bit (not reflected in github yet) can you update the npm version and tell me if you are able to see the typing?

**Comment by Teranode** [comment] 2022-05-08 05:26
closing due to no reply.

**Closed by Teranode** 2022-05-08 05:26 UTC
Labels: help wanted
